language: java
jdk:
  - openjdk11

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY      # travis 레포에 설정된 값
    secret_access_key: $AWS_SECRET_KEY  # travis 레포에 설정된 값
    bucket: s3-travis-ci-bbpsp          # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private                # zip 파일 접근을 private으로
    local_dir: deploy           # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: s3-travis-ci-bbpsp
    key: freelec-springboot2-webservice.zip
    bundle_type: zip
    application: code-deploy-bbpsp
    deployment_group: code-deploy-bbpsp-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - dmlwo08@naver.com

