spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(QwSoVTvxVFUJBLEiRx+v1QzzBWUH/QYYh1phzQbnZ7VgBm36zql1wd9ZH5mtGTNhlhgTSxleaCXYbrbe1LRkAumatKcSofJrYk8Lmdie7SlDExUUvkdhEw==)
    username: ENC(43POj+5V+uMu0paVRS7XEbKlSe6yLFmb)
    password: ENC(0/hmDqqaUMpRs85XbhrKWk1GZCMe8B3Q)

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      #        show_sql: true // sys out으로 로그가 찍힘
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  level:
    org.hibernate.SQL: debug # 로거로 로그가 찍힘
#    org.hibernate.type: trace

server:
  port: 8081